ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_memo TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS promotion_code TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS promotion_label TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS promotion_discount INTEGER NOT NULL DEFAULT 0;
